### ISSUE TITLE
Error: No provider for "framework:jquery-2"! (Resolving: framework:jquery-2)

### ISSUE THREAD

**Issue by gspeiliu** [bessdsv/karma-jasmine-jquery#19]
Hi,

I am using karma to test my js files which also using jquery. I downloaded all of the karma, karma-jasmine, jasmine-core, karma-coverage and also karma-jasmine-jquery. However, when I tried to add jquery-1.3.2, as the README file directions, into the frameworks array, the mvn package shows the error: Error: No provider for "framework:jquery-1"! (Resolving: framework:jquery-1). I also did not find any jquery resources under the node_modules files. I am stuck with this problem. Does anyone have any idea? any advice will be appreciated. OS: windows 10, all of the plugins are installed by npm install. all of these dependencies are all included in package.json file.

Thank you. :)

**Comment by dlarr** [comment]
Hello :) Same issue here. Did you manage this ?
