### ISSUE TITLE
jQuery is undefined

### ISSUE THREAD

**Issue by sklyukin** [bessdsv/karma-jasmine-jquery#2]
During karma start I got. 

```
Uncaught ReferenceError: jQuery is not defined
  at /var/www/pullr/node_modules/karma-jasmine-jquery/lib/setJqueryForJasminJqueryPlugin.js:1
```

So seems that is not enough for `karma.conf.js`
```
`frameworks: ['jasmine','jasmine-jquery'],`
```

**Comment by husa** [comment]
@bessdsv Since you've added ```jasmine-jquery``` to the repository, maybe you can also add ```jquery```, and include it as well.
Because, at the moment, it's not so clear that local jQuery should be included. Personally I thought it's bundled within a plugin.

**Comment by bessdsv** [comment]
@husa I added jquery in the file jqueryForJasmineJqueryPlugin.js.
version 2.1.1.
